apiVersion: apps/v1
kind: Deployment
metadata:
  name: cyberpunk-backend
  namespace: cyberpunk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cyberpunk-backend
  template:
    metadata:
      labels:
        app: cyberpunk-backend
    spec:
      containers:
        - name: backend
          # Замените на реальный образ из вашего registry, собранный из Dockerfile
          image: vaiz82/cyberpunk-backend                             ## your-registry/cyberpunk-backend:1.0
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: db-credentials
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cyberpunk-backend
  namespace: cyberpunk
spec:
  type: ClusterIP
  selector:
    app: cyberpunk-backend
  ports:
    - port: 80
      targetPort: 8000
